train_path: "Cleaned_Proposed_Data_Collection.csv"
test_path: "Cleaned_food_drive_data.csv"
models_dir: models
model_filename: random_forest_classifier_model.pkl
mlflow_experiment_name: "FoodDriveExperiment"
random_forest:
  n_estimators: 100
  max_depth: 10
param_grids:
    RandomForestClassifier: 
        n_estimators: [50, 100, 200]
        max_depth: [None, 10, 20, 30]  
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
    DecisionTreeClassifier: 
        max_depth: [None, 10, 20, 30]  
        min_samples_split: [2, 5, 10]  
        min_samples_leaf: [1, 2, 4]  
        criterion: ["gini", "entropy"] 
  